---
title: "IS6481 | Lab 4 -- Dashboard Creation"
output: 
  html_document: 
    theme: cosmo
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# options(width = 120)
```

# Objectives
This is the third (and final) portion of this series of labs where we link strategy and analytics via a set of metrics. The set of metrics should be designed to support a specific initiative. You will likely remember that we are supporting the strategic initiative of **increase monthly per-customer revenue** for a theoretical/fictional DVD rental shop. The primary task of this lab is to create a dashboard of metrics that you planned in lab 2.

## Instructions
The following resources should help you learn how to design charts and graphs (referred to as cards) in Domo.

* [Adding a page](https://www.youtube.com/watch?v=yL6CWQ9w4p8)
* [Analyzer Introduction](https://www.youtube.com/watch?v=FjkmAgpTT7U)
* [Beast Mode Intro](https://www.youtube.com/watch?v=iEJ9x7-Tgw0)
* [Case Statements in Calculated Fields](https://www.youtube.com/watch?v=o9_kkTFTqkI)
* [Dashboard Strategy](https://www.youtube.com/watch?v=7ULGsdibovI)

Create a page in Domo and design the page to answer the objectives you have identified for this project. Feel free to create this as a default page or as a dashboard/story.

When finished, share the page with the group called 'Instructor/TA' by clicking the share icon in the top right of the screen (just to the left of the wrench icon). Then click "Share" and type in the name of the group.

## To Turn In
After sharing the page as described above, finalize the assignment by turning in a writeup of the assignment that includes the following.

* A link to the page/dashboard you created.
* An explination of the page or dashboard.
* A description of how it maps to the strategic initiative of **increase monthly per-customer revenue**.
* A discussion of your experience with this project including notes on any gaps between your plan and the final product.

